language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
 
script:
  - mozroots --import --sync
  - wget http://nuget.org/nuget.exe
  - mono --runtime=v4.0 ./nuget.exe restore
  - xbuild
  - nunit-console ./AllureCSharpCommons.Tests/bin/Debug/AllureCSharpCommons.Tests.dll
